From openjdk:8-jdk-alpine
ARG JAR_FILE=target/*.jar
ARG SPRING_PROFILES_ACTIVE
RUN echo $SPRING_PROFILES_ACTIVE
ENV SPRING_PROFILES_ACTIVE = $SPRING_PROFILES_ACTIVE
COPY ${JAR_FILE} app.jar
ENTRYPOINT ["java","-jar","/app.jar"]